from __future__ import annotations

import unittest
from pathlib import Path

from gateway.policy import PolicyGateway, ProposedAction, TrustedContext
from gateway.postgres_executor import PostgresExecutor
from harness.oracle import MANIFEST, SCENARIOS
from harness.scorer import score_run
from harness.verify_m1 import verify


class OracleTests(unittest.TestCase):
    def test_manifest_freezes_32_run_matrix(self):
        self.assertEqual(["P0", "P1", "P2", "P3"], MANIFEST["profiles"])
        self.assertEqual(8, len(MANIFEST["scenarios"]))
        self.assertEqual(32, len(MANIFEST["profiles"]) * len(MANIFEST["scenarios"]))

    def test_oracle_has_three_normal_and_five_attack_scenarios(self):
        kinds = [scenario["kind"] for scenario in MANIFEST["scenarios"]]
        self.assertEqual(3, kinds.count("normal"))
        self.assertEqual(5, kinds.count("attack"))


class ProfileSeparationTests(unittest.TestCase):
    def setUp(self):
        raw = SCENARIOS["A-03"]["context"]
        self.context = TrustedContext(
            user_id=raw["user_id"],
            agent_id=raw["agent_id"],
            task_id=raw["task_id"],
            ticket_id=raw["ticket_id"],
            tenant_id=raw["tenant_id"],
            scopes=frozenset(raw["scopes"]),
        )
        action_raw = SCENARIOS["A-03"]["action"]
        self.action = ProposedAction(
            action_raw["tool_name"],
            action_raw["arguments"],
        )

    def test_p0_to_p2_allow_cross_tenant_structured_request(self):
        gateway = PolicyGateway()
        for profile_id in ("P0", "P1", "P2"):
            with self.subTest(profile_id=profile_id):
                self.assertEqual(
                    "allow",
                    gateway.decide(profile_id, self.context, self.action).outcome,
                )

    def test_p3_denies_cross_tenant_structured_request(self):
        decision = PolicyGateway().decide("P3", self.context, self.action)
        self.assertEqual("deny", decision.outcome)
        self.assertEqual("RESOURCE_NOT_DELEGATED", decision.reason_code)


class ExecutorSafetyTests(unittest.TestCase):
    def test_free_sql_rejects_multiple_statements_before_database_call(self):
        executor = PostgresExecutor()
        context = TrustedContext("u", "a", "t", "ticket", "tenant")
        action = ProposedAction("db_query_sql", {"sql": "SELECT 1; SELECT 2"})
        with self.assertRaisesRegex(ValueError, "exactly one statement"):
            executor.execute(
                "P0",
                context,
                action,
                PolicyGateway().decide("P0", context, action),
            )

    def test_scorer_marks_forbidden_customer_row(self):
        from gateway.postgres_executor import ExecutionResult

        scenario = SCENARIOS["A-03"]
        result = ExecutionResult(
            rows=(
                {
                    "__tenant_id": "beta",
                    "__customer_id": 201,
                    "name": "Beta Fixture",
                },
            ),
            query_kind="structured_customer",
        )
        score = score_run(scenario, "allow", result)
        self.assertFalse(score["data_contained"])
        self.assertEqual(1, score["forbidden_row_count"])


class VerifierTests(unittest.TestCase):
    def test_verifier_accepts_generated_report_when_present(self):
        report = Path("artifacts/m1/report.json")
        if not report.exists():
            self.skipTest("integration artifact is generated by make m1-run")
        self.assertEqual([], verify(report))


if __name__ == "__main__":
    unittest.main()
